vapor-ware/synse-cli

- .gitignore
- Makefile
fixes #55 
Note: Some of the targets do not run successfully. There will be subsequent PRs needed for cleaning up some tests, linting, etc.
> add a Makefile with useful development targets

- commands/commands.go
- commands/hosts/active.go
- commands/hosts/add.go
- commands/hosts/change.go
- commands/hosts/cmd.go
- commands/hosts/delete.go
- commands/hosts/list.go
some more quick iteration skeleton work
> add in stubs for the 'hosts' command

- commands/commands.go
- commands/server/config.go
- commands/server/info.go
- commands/server/read.go
- commands/server/scan.go
- commands/server/status.go
- commands/server/transaction.go
- commands/server/version.go
- commands/server/write.go
- scheme/info.go
- scheme/write.go
- utils/table.go
this fills out more commands for the v2 API
- scan
- info
- read
- write 
- transaction
note that I still need to add in comments/docs, still need to do some cleanup+optimization, and still need to figure out the best way to format all the outputs, among other things. 
after this, I'll put together a PR that starts to clean things up, add comments, etc.
> fill out more commands for v2

- commands/commands.go
- commands/hosts/cmd.go
- commands/server/config.go
- commands/server/info.go
- commands/server/read.go
- commands/server/scan.go
- commands/server/status.go
- commands/server/transaction.go
- commands/server/version.go
- commands/server/write.go
- utils/command.go
- utils/errors.go
- utils/http.go
- utils/output.go
this cleans up a bunch of duplicate code by breaking things out into helper functions.
> add helpers for some common functionality

- commands/hosts/add.go
- commands/hosts/change.go
- commands/hosts/delete.go
> use argument checking utils for hosts subcommands

- commands/hosts/list.go
> add sorting for hosts list output

- commands/server/config.go
- commands/server/info.go
- commands/server/status.go
- commands/server/transaction.go
- commands/server/version.go
- flags/command.go
- scheme/status.go
- scheme/version.go
- utils/output.go
> allow yaml and json output formats for various commands 

- README.md
- commands/commands.go
- commands/completion.go
- flags/command.go
- utils/shellcompletion.go
add docs to the readme, update command organization, add a bit in the completion logic that will create the required directory if it doesn't exist.
> update completion command

- pkg/commands/completion.go
- pkg/utils/shellcompletion.go
> make completion script output directory configurable

- pkg/client/client.go
- pkg/commands/server/transaction.go
- pkg/completion/completion.go
related to #133 
sets up bash completion for synse server transaction checking
> add autocomplete for server transaction checking

- Gopkg.lock
- Gopkg.toml
- pkg/commands/commands.go
- pkg/commands/update.go
Add's an [automatic in-line updater](github.com/timfallmk/overseer) pointed to the releases page of this repo.
Closes #152
> Add an automatic updater function

- pkg/config/config.go
> Spelling mistake

- .circleci/config.yml
Upload binaries to slack channel when released.
> Upload binaries to slack

- README.md
add a few missing pieces to the curl command to specify data type and to allow redirects
> update readme example for getting via curl

- .circleci/config.yml
- Makefile
- cmd/synse.go
- pkg/formatters/format.go
- pkg/version/version.go
This PR contains:
- updates to CI config to better align with other projects
- updates to Makefile
- update how versioning is done in the CLI
> Updates to CI flow, versioning, and Makefile

- pkg/scheme/hosts_list.go
- pkg/scheme/read.go
> fix some output formatting inconsistencies

- pkg/client/grpc.go
- pkg/commands/plugin/cmd.go
- pkg/commands/plugin/health.go
- pkg/commands/plugin/health_test.go
- pkg/commands/plugin/testdata/health.error.none.golden
- pkg/commands/plugin/testdata/health.error.tcp.no_backend.golden
- pkg/commands/plugin/testdata/health.error.unix.no_backend.golden
- pkg/formatters/plugins.go
> Add command for viewing plugin health via rpc call

- internal/test/utils.go
- pkg/client/client_test.go
- pkg/commands/server/capabilities_test.go
- pkg/commands/server/config_test.go
- pkg/commands/server/info_test.go
- pkg/commands/server/plugins_test.go
- pkg/commands/server/pluginshealth_test.go
- pkg/commands/server/pluginsinfo_test.go
- pkg/commands/server/scan_test.go
- pkg/commands/server/status_test.go
- pkg/commands/server/transaction_test.go
- pkg/commands/server/version_test.go
- pkg/commands/server/write_test.go
- This PR completes #182. It refactors `synse server` test cases and add missing client endpoints' test cases. This should raise the overall coverage a little bit.
- GRPC/plugin related functions are the ones that we haven't fully covered yet. I think this will involve more investigations on how to do them properly. Here is a [resource](https://github.com/grpc/grpc-go/blob/master/Documentation/gomock-example.md) that might be helpful.
> Update latest test cases

- Gopkg.lock
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/grpc.go
- pkg/commands/plugin/capabilities.go
- pkg/commands/plugin/cmd.go
- pkg/commands/plugin/devices.go
- pkg/commands/plugin/health.go
- pkg/commands/plugin/read.go
- pkg/commands/plugin/read_test.go
- pkg/commands/plugin/readcached.go
- pkg/commands/plugin/readcached_test.go
- pkg/commands/plugin/testdata/readcached.error.none.golden
- pkg/commands/plugin/testdata/readcached.error.tcp.no_backend.golden
- pkg/commands/plugin/testdata/readcached.error.unix.no_backend.golden
- pkg/commands/plugin/transaction.go
- pkg/commands/server/cmd.go
- pkg/commands/server/read.go
- pkg/commands/server/readcached.go
- pkg/commands/server/readcached_test.go
- pkg/commands/server/testdata/readcached.success.json.golden
- pkg/commands/server/testdata/readcached.success.pretty.golden
- pkg/commands/server/testdata/readcached.success.yaml.golden
- pkg/formatters/read.go
- pkg/formatters/readcached.go
- pkg/scheme/capabilities.go
- pkg/scheme/devices.go
- pkg/scheme/info.go
- pkg/scheme/read.go
- pkg/scheme/readcached.go
> Add 'readcached' command

- pkg/cmd/completion.go
- pkg/cmd/context/add.go
- pkg/cmd/context/printer.go
- pkg/cmd/context/root.go
- pkg/cmd/plugin/devices.go
- pkg/cmd/plugin/health.go
- pkg/cmd/plugin/metadata.go
- pkg/cmd/plugin/read.go
- pkg/cmd/plugin/read_cache.go
- pkg/cmd/plugin/root.go
- pkg/cmd/plugin/test.go
- pkg/cmd/plugin/transaction.go
- pkg/cmd/plugin/version.go
- pkg/cmd/plugin/write.go
- pkg/cmd/server/root.go
- pkg/config/config.go
- pkg/utils/grpc.go
> add capabilities for supplying plugin certificate

- pkg/cmd/completion.go
- pkg/cmd/root.go
> bash completion

- .goreleaser.yml
- .jenkins
This PR:
- updates CI to use the `golang-alpha` agent
- other various updates and improvements to CI
> updates for CI

- pkg/cmd/context/add.go
- pkg/cmd/context/list.go
- pkg/cmd/plugin/devices.go
- pkg/cmd/plugin/health.go
- pkg/cmd/plugin/metadata.go
- pkg/cmd/plugin/read.go
- pkg/cmd/plugin/read_cache.go
- pkg/cmd/plugin/test.go
- pkg/cmd/plugin/transaction.go
- pkg/cmd/plugin/version.go
- pkg/cmd/root.go
- pkg/cmd/server/config.go
- pkg/cmd/server/info.go
- pkg/cmd/server/plugins/health.go
- pkg/cmd/server/plugins/info.go
- pkg/cmd/server/plugins/list.go
- pkg/cmd/server/read.go
- pkg/cmd/server/read_cache.go
- pkg/cmd/server/scan.go
- pkg/cmd/server/status.go
- pkg/cmd/server/stream.go
- pkg/cmd/server/tags.go
- pkg/cmd/server/transaction.go
- pkg/cmd/server/version.go
- pkg/cmd/server/write.go
- pkg/cmd/version.go
- pkg/config/config.go
This PR:
- adds and updates debug logging throughout the CLI
fixes #83
> add and update debug logging

- .goreleaser.yml
- README.md
- docker-compose.yaml
- go.mod
- go.sum
- internal/test/grpc.go
This PR:
- updates dependencies
- updates CI config for generated changelogs
- renames synse.yaml to docker-compose.yaml
> v3 updates

- .jenkins
- Makefile
updates the ci pipeline to use the ci-shared lib
fixes #234
> ci: update ci config to use shared pipelines

- .github/workflows/release.yml
xref: https://github.com/vapor-ware/synse-emulator-plugin/pull/120
> Fix release trigger

- pkg/config/config.go
Enhancement:
is providing better response while adding context. This will throw warning while adding different named context with same type and same address value.
> Enhancement: Context warning
