- commands/commands.go
- commands/hosts/active.go
- commands/hosts/add.go
- commands/hosts/change.go
- commands/hosts/cmd.go
- commands/hosts/delete.go
- commands/hosts/list.go
- config/config.go
- config/utils.go
- flags/flags.go
- synse.go
- utils/table.go
this adds functionality for the `synse hosts` subcommands
- active
- add
- change
- delete
- list
there is still cleanup to be done, but this gets the base functionality in. 
if no config file is detected, one will be created to persist host info. if one exists, it will be updated.
> add the functionality for the 'hosts' subcommands

- scheme/config.go
fixes #84 
turns out that when specifying multiple struct field annotations, you need to separate with a space, not a comma.
> fix config output yaml formatting

- commands/server/scan.go
- flags/command.go
fixes #77 
this adds basic filtering. right now only for type. there may be a better way to do this and it certainly could be cleaned up / organized better, but this at least gets it in.
```
edaniszewski ~/go/src/github.com/vapor-ware/synse-cli (scan-filter) ➜ ./build/synse scan
ID                                           INFO                        TYPE         
--------------------------------------------------------------------------------------
rack-1-vec-329a91c6781ce92370a3c38ba9bf35b2  Synse Temperature Sensor 4  temperature  
rack-1-vec-83cc1efe7e596e4ab6769e0c6e3edf88  Synse Temperature Sensor 2  temperature  
rack-1-vec-d29e0bd113a484dc48fd55bd3abad6bb  Synse backup LED            led          
rack-1-vec-db1e5deb43d9d0af6d80885e74362913  Synse Temperature Sensor 3  temperature …
```
> add basic filtering to scan command

- commands/plugin/metainfo.go
- commands/plugin/read.go
- commands/plugin/transaction.go
- commands/plugin/write.go
- formatters/format.go
- formatters/plugin/metainfo.go
- formatters/plugin/read.go
- formatters/plugin/transaction.go
- formatters/plugin/write.go
this PR generalizes how output formatting is done for commands, so now there is a common backend/pattern to follow for commands. 
still need to update the formatting of a bunch of commands to use this, but the plugin commands all use this and output correctly. also with these changes, we should be able to test expected command output
> generalize output formatting

- commands/hosts/active.go
- commands/hosts/add.go
- commands/hosts/change.go
- commands/hosts/delete.go
- commands/hosts/list.go
- config/config.go
- config/utils.go
- formatters/format.go
- formatters/hosts/list.go
this updates the output formatting for the `hosts` commands so they use the generalized formatting utils put together in an earlier PR
> update formatting for 'hosts' commands

- pkg/formatters/read.go
- pkg/formatters/transaction.go
- pkg/utils/utils.go
fixes #103 
```
edaniszewski ~/go/src/github.com/vapor-ware/synse-cli (timestamp-formatting *) ➜ ./build/synse scan
RACK      BOARD     DEVICE                             INFO                         TYPE
rack-1    vec       329a91c6781ce92370a3c38ba9bf35b2   Synse Temperature Sensor 4   temperature
rack-1    vec       83cc1efe7e596e4ab6769e0c6e3edf88   Synse Temperature Sensor 2   temperature
rack-1    vec       d29e0bd113a484dc48fd55bd3abad6bb   Synse backup LED             led
rack-1    vec       db1e5deb43d9d0af6d80885e74362913   Synse Temperature Sensor 3   temperature
rack-1    vec       eb100067acb0c054cf877759db376b03   Synse Temperature Sensor 1   temperature
rack-1    vec       eb9a56f95b5bd6d9b51996ccd0f2329c   Synse Fan                    fan
rack-1    vec …
```
> update timestamp formatting

- pkg/client/client.go
- pkg/commands/commands.go
- pkg/commands/server/config.go
- pkg/commands/server/plugins.go
- pkg/commands/server/plugins_test.go
- pkg/commands/server/read.go
- pkg/commands/server/scan.go
- pkg/commands/server/status.go
- pkg/commands/server/transaction.go
- pkg/commands/server/version.go
- pkg/commands/server/write.go
- pkg/formatters/plugins.go
- pkg/scheme/plugins.go
adds support for the Synse Server "plugins" command which was recently added to Synse Server. This will list all of the plugins currently configured with Synse Server. 
fixes #110
> add synse server 'plugins' command

- pkg/commands/commands.go
- pkg/commands/server/cmd.go
- pkg/commands/server/config.go
- pkg/commands/server/config_test.go
- pkg/commands/server/doc.go
- pkg/commands/server/info.go
- pkg/commands/server/info_test.go
- pkg/commands/server/plugins.go
- pkg/commands/server/plugins_test.go
- pkg/commands/server/read.go
- pkg/commands/server/read_test.go
- pkg/commands/server/scan.go
- pkg/commands/server/scan_test.go
- pkg/commands/server/status.go
- pkg/commands/server/status_test.go
- pkg/commands/server/transaction.go
- pkg/commands/server/transaction_test.go
- pkg/commands/server/version.go
- pkg/commands/server/version_test.go
- pkg/commands/server/write.go
- pkg/commands/server/write_test.go
fixes #127 
```
➜ ./build/synse 
NAME:
synse - Command line tool for interacting with Synse components
USAGE:
synse [global options] command [command options] [arguments...]
VERSION:
0.1.0
COMMANDS:
hosts       Manage Synse Server instances
plugin      Interact with Synse Plugins
server      Interact with Synse Server
completion  Generate shell completion scripts for bash or zsh
help, h     Shows a list of commands or help for one command
GLOBAL OPTIONS:
--debug, -d     enable debug mode
--config        display the current CLI configuration
--format value  specify the output format for a command (default: "pretty")
--help, -h      show help
--version, -v   print the version
```
```
➜ ./build/synse server
NAME:
synse server - Interact with Synse Server
USAGE:
synse server command [command …
```
> move server commands to a subcommand

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/scheme/error.go
before, when we got an error back from synse server, we got error text that just said there was an error. now, provide context for the error
```
➜ synse server read rack-1 vec eb100067acb0c054cf877759db376a34
Synse Server responded with error: 
{
"http_code": 500,
"error_id": 4000,
"description": "device not found",
"timestamp": "2018-03-09 20:30:10.982730",
"context": "rack-1/vec/eb100067acb0c054cf877759db376a34 does not correspond with a known device."
}
```
fixes #121 
Not sure this is the best way to format the output, but we at least get useful info out with this change. Formatting can be updated later if need be.
> return synse error json in event of error

- pkg/formatters/transaction.go
fixes #120
before
```console
$ synse server transaction baj8p7saub700204f67g
STATUS    STATE     CREATED                        UPDATED
done      error     Mon Mar 12 14:20:15 UTC 2018   Mon Mar 12 14:20:15 UTC 2018
```
after
```console
$ synse server transaction baj8p7saub700204f67g
STATUS    STATE     CREATED                        UPDATED                        MESSAGE
done      error     Mon Mar 12 14:20:15 UTC 2018   Mon Mar 12 14:20:15 UTC 2018   unsupported command for state action: foo
```
and for a response with no errors
```console
$ synse server transaction baj8rng81880027upp8g
STATUS    STATE     CREATED                        UPDATED                        MESSAGE
done      ok        Mon Mar 12 14:25:34 UTC 2018   Mon Mar 12 14:25:35 UTC 2018   ok
```
> add message field to transaction response

- docker/Dockerfile
Fixes #106
This won't work and can't be merged until `2.0` lands due to vendored dependedncies
Merge after merging #138
> Add back a minimal dockerfile

- pkg/completion/completion.go
Before, the filtering here was pretty basic and just returned all the options for rack/board/device.
Now, it will show all racks, then it will only show boards on that rack, then it will only show devices on that board.
> filter completion results for read/write to only show relevent devices

- pkg/commands/plugin/write.go
- pkg/commands/server/write.go
changes to the docs on valid LED write values. the "blink" action was changed so that blink is now a value of the power state.
> update docs for led blink state change

- .circleci/config.yml
fixes #158 
this wasn't an issue before, not sure why it is now, but reduced the number of parallel builds by quite a bit so it doesn't run into the memory issue
> reduce number of parallel builds

- pkg/commands/plugin/read.go
- pkg/commands/plugin/read_test.go
- pkg/commands/plugin/write.go
- pkg/commands/server/write.go
This PR updates existing functionalities of plugin subcommands (`synse plugin COMMAND`) over gRPC 1.0 changes. It is a continuation of #177 to finish off #172.
> Update plugin subcommands due to gRPC 1.0 changes

- pkg/formatters/capabilities.go
- pkg/formatters/scan.go
- pkg/scheme/capabilities.go
- pkg/scheme/devices.go
This PR basically moves the scheme output of `capabilities` and `devices` to the scheme folder for consistency.
> Refactor pretty output scheme of `capabilities` and `devices`

- pkg/commands/server/read.go
- pkg/commands/server/read_test.go
This PR attempts to fix #179 and #187's comment. The idea is, for a `read` command that eventually returns a `nil` response for the formatter, which returns *nothing* to user, we want to validate it first. By checking the returned error from Synse Server via `info` endpoint, we make sure that `nil` is never the case. User will either receive a good response or an error.
If this PR is approved, I will go ahead and fix all the remaining test cases for read and open a seperate PR for that.
> Validate read input before filtering

- pkg/commands/server/read_test.go
- pkg/commands/server/testdata/read.success.json.multiple_flags.golden
- pkg/commands/server/testdata/read.success.json.single_flag.golden
- pkg/commands/server/testdata/read.success.pretty.multiple_flags.golden
- pkg/commands/server/testdata/read.success.pretty.single_flag.golden
- pkg/commands/server/testdata/read.success.yaml.multiple_flags.golden
- pkg/commands/server/testdata/read.success.yaml.single_flag.golden
This PR is a part of #182. It adds more test cases for `synse server read` using single flag and multiple flags. Discovered #192 while doing this.
> Add missing flag test cases for `synse server read`

- .jenkins
- Makefile
- go.mod
This PR:
- removes the dist folder from goreleaser in CI
- tidies go.mod file
The previous alpha tag release [failed CI](https://build.vio.sh/blue/organizations/jenkins/vapor-ware%2Fsynse-cli/detail/3.0.0-alpha.1/1/pipeline), apparently for these reasons. I'm not 100% sure why go.mod was in a dirty state, but I think this might fix it.
> remove dist folder, tidy dependencies

- .goreleaser.yml
This PR:
- updates the goreleaser config so that it will automatically update the homebrew formula whenever a new tagged version is released.
> ci: update goreleaser to automatically update homebrew formula

- Makefile
- go.mod
- go.sum
This PR:
- picks up the latest SDK update, which allows for device_info in the reading model.
- the cli does not print out the info in the tabular view -- if thats desired, it can be added as a separate issue
- the info will be present when printing out in json/yaml format, assuming the plugin/synse-server are of a version which supports the grpc message/sdk update
- adds an explicit local build target for linux
> deps: update SDK dependency

- .goreleaser.yml
- .jenkins
- VIO-1911 Remove yaml not compatible with latest goreleaser
- VIO-1911 Build with latest goreleaser logic
> VIO-1911 Bump logic to latest goreleaser

- README.md
- go.mod
- go.sum
- pkg/config/config.go
- pkg/utils/http_test.go
Previously if running the cli from the home dir without having `$HOME`, the CLI would return a nil err. This PR ensures it would actually persist the config.
Closes #239 
Signed-off-by: Sam Foo <sam.foo@vapor.io>
> Fix CLI not persisting config changes in HOME

- .github/workflows/release.yml
- .goreleaser.yml
Changes for synse-cli release v3.0.1.
1) Check release.
```
[sdicki@Phoenix] ~/Development/git/vapor-io/synse-cli$ goreleaser check
• loading config file                              file=.goreleaser.yml
• checking configuration...
• DEPRECATED:  brews.tap  should not be used anymore, check https://goreleaser.com/deprecations#brewstap for more info
• .goreleaser.yml                                  error=configuration is valid, but uses deprecated properties
⨯ command failed                                   error=1 out of 1 configuration file(s) have issues
```
2) Change `tap:` to `repository:` in .goreleaser.yml
3) Re-check release.
```
[sdicki@Phoenix] ~/Development/git/vapor-io/synse-cli$ goreleaser check
• loading config file                              file=.goreleaser.yml
• …
```
> Removed deprecated use of tap: for repository:

- pkg/cmd/context/root.go
- pkg/cmd/context/testdata/unset.extra-args.golden
- pkg/cmd/context/testdata/unset.nonexisting.golden
- pkg/cmd/context/unset.go
- pkg/cmd/context/unset_test.go
- pkg/config/config.go
This PR:
- Adds a new `unset` command to unset a current active context
Question - should an error be raised if the current context is not the one provided?
[VIO-3177]
[VIO-3177]: https://vaporio.atlassian.net/browse/VIO-3177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add unset context command
